
tp2:  ExcepcionAlLeerEntrada.cpp knn.cpp main.cpp parseadorDeArchivoConClasesImagenes.cpp parseadorDeArchivoTestIn.cpp
	g++ -std=c++11 ExcepcionAlLeerEntrada.cpp knn.cpp main.cpp parseadorDeArchivoConClasesImagenes.cpp parseadorDeArchivoTestIn.cpp -o tp2

